## Utility client example
##

Import('env')
Import('env_cpp11')
Import('boostlibs')
Import('platform_libs')
Import('polyfill_libs')

env = env.Clone ()
env_cpp11 = env_cpp11.Clone ()

prgs = []

# if a C++11 environment is available build using that, otherwise use boost
if env_cpp11.has_key('WSPP_CPP11_ENABLED'):
   ALL_LIBS = boostlibs(['system'],env_cpp11) + [platform_libs] + [polyfill_libs]
   prgs += env_cpp11.Program('utility_client_tls', ["utility_client_tls.cpp","tls_util.cpp","tls_util.hpp"], LIBS = ALL_LIBS)
else:
   ALL_LIBS = boostlibs(['system','random'],env) + [platform_libs] + [polyfill_libs]
   prgs += env.Program('utility_client_tls', ["utility_client_tls.cpp","tls_util.cpp","tls_util.hpp"], LIBS = ALL_LIBS)

Return('prgs')